import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

// Vite-compatible `?raw` imports: print CSS ships as raw strings injected via
// <style> at runtime — CSS snippets never reach Obsidian's printToPDF() (#28).
// Vite/vitest support `?raw` natively; this plugin teaches esbuild the same.
const rawImports = {
  name: "raw-imports",
  setup(build) {
    build.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: path.resolve(args.resolveDir, args.path.replace(/\?raw$/, "")),
      namespace: "raw-text",
    }));
    build.onLoad({ filter: /.*/, namespace: "raw-text" }, async (args) => ({
      contents: await readFile(args.path, "utf8"),
      loader: "text",
    }));
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
yaae - Why Author Anywhere Else
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "ES2022",
  plugins: [rawImports],
  logLevel: "info",
  // Production writes meta.json so scripts/check-bundle-inputs.sh can assert
  // what actually entered the bundle. Grepping the minified main.js cannot:
  // minification renames every symbol, so a grep returns a confident negative
  // whether or not the bench harness shipped.
  metafile: prod,
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  platform: "node",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
});

if (prod) {
  const result = await context.rebuild();
  await writeFile("meta.json", JSON.stringify(result.metafile), "utf8");
  process.exit(0);
} else {
  await context.watch();
}
